#pragma once

#define CHUNK_SIZE 16 // Must be a power of 2
#define CHUNK_MULTIPLIER_EXPONENT 0

#define DATA_CHUNK_SIZE CHUNK_SIZE
#define DATA_CHUNK_TOTAL_SIZE (DATA_CHUNK_SIZE * DATA_CHUNK_SIZE * DATA_CHUNK_SIZE)

#define CHUNK_MULTIPLIER (1 << CHUNK_MULTIPLIER_EXPONENT)
#define RENDER_CHUNK_SIZE (CHUNK_MULTIPLIER * CHUNK_SIZE)

#define VOXEL_MULTITHREAD_STAT 1

#define MATERIALS_ARE_COLOR 0