// Copyright 2019 Phyronnaz

#pragma once

#include "CoreMinimal.h"
#include "Misc/CoreMisc.h"
#include "Misc/MessageDialog.h"
#include "Misc/UObjectToken.h"
#include "UnrealClient.h"
#include "EditorViewportClient.h"
#include "Editor.h"
#include "ObjectTools.h"
#include "AssetToolsModule.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/Notifications/SNotificationList.h"
#include "Framework/SlateDelegates.h"
#include "Framework/Notifications/NotificationManager.h"
#include "DetailLayoutBuilder.h"
#include "DetailCategoryBuilder.h"
#include "DetailWidgetRow.h"
#include "AssetTypeActions_Base.h"
#include "SCommonEditorViewportToolbarBase.h"
#include "EngineUtils.h"
#include "Logging/TokenizedMessage.h"
#include "Logging/MessageLog.h"
#include "UObject/Stack.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "Kismet2/KismetDebugUtilities.h"
#include "Kismet2/KismetEditorUtilities.h"

#include "AssetTools/AssetTypeActions_VoxelBase.h"